### ISSUE TITLE
'ng' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by MrForJewel** [bojue/Web-editor-server-node#2]
'ng' 不是内部或外部命令，也不是可运行的程序

**Comment by bojue** [comment]
@MrForJewel 我在Web-Editor项目的[Issues](https://github.com/bojue/Web-Editor/issues/41) 回复过了，server项目是基于Node.js写的，可以单独运行，ng是angular-cli上的命令，出现这个问题最可能是没有安装angular-cli，可以通过安装全局的angular-cli解决，也可以查看一下版本号是否有问题
